flowbit-team/flowbit

src/lib/Chart.ts
=> [bugfix] build 에러

package.json, pnpm-lock.yaml, src/app/news/index.tsx, src/components/app/news/selector.tsx, src/components/app/predict/newsletter/news-card.tsx, src/hooks/api/newsletter/UseApiNewLetter.ts, src/routes/index.tsx, src/style/variable.ts, src/utils/util.ts
> ### #33, #38 뉴스레터 레이아웃 구성 및 API 연동
---
- 뉴스레터 레이아웃 구성을 진행하였습니다.
- Tanstack 무한 스크롤을 이용한 API 연동을 진행하였습니다.
- 커밋 내용 참조
- closes: #33 
- closes: #38
=> feat: #33, #38 뉴스레터 레이아웃 구성 및 API 연동

index.html
> ### 플로우빗 파비콘 및 타이틀 변경
---
- 플로우빗 파비콘 및 타이틀 변경
- 플로우빗 파비콘 및 타이틀 변경
이전 이슈에 `index.html`이 누락되어 한번 더 PR을 올립니다.
-
=> feat: #44 플로우빗 파비콘 및 타이틀 변경 (중복)

vercel.json
=> fix: fix vercel 404 enviroment

src/hooks/api/newsletter/UseApiNewLetter.ts
> ### 뉴스레터 데이터 조회 문제 수정
---
- 뉴스레터 데이터 조회 문제를 수정했습니다 (알고보니 단일 뉴스레터랑 같은 쿼리키를 사용하고 있던..)
- `UseApiNewLetter.ts`
- closes: #42
=> fix: #42 뉴스레터 데이터 조회 문제 수정

src/app/news/index.tsx
=> [news letter] 케러셀 연동

src/app/news/index.tsx, src/components/app/news/selector.tsx, src/components/app/predict/newsletter/news-card.tsx, src/components/app/predict/newsletter/news-content.tsx, src/components/app/predict/newsletter/news-image.tsx, src/components/app/predict/newsletter/news-tag.tsx, src/hooks/api/newsletter/UseApiIncreaseViews.ts, src/hooks/api/newsletter/UseApiNewLetter.ts
> ### 뉴스레터 API 연동
---
- 뉴스레터 API 연동을 진행하였습니다.
- 커밋 내용 참고 부탁드립니다.
closes: #51 
-
=> feat: #51 뉴스레터 API 연동

src/app/predict/index.tsx, src/components/app/predict/chart/chart.tsx, src/components/app/predict/fitness/fitness.tsx, src/lib/Chart.ts, src/style/global.css
---
- 비트 코인 예측 페이지 반응형 작업
- 
-
=> [market performance] 비트코인 예측 페이지 반응형 작업

package.json, pnpm-lock.yaml, src/app/news/index.tsx, src/components/app/news/selector.tsx
> ### 뉴스레터 카테고리 및 정렬 변경 시, 스크롤이 초기화되는 현상이 발생합니다.
---
- 스크롤 관련 버그를 수정하였습니다.
- 커밋 내용을 참조해주세요
- closes: #57
=> fix: #57 뉴스레터 카테고리 및 정렬 변경 시, 스크롤이 초기화되는 현상 수정

src/app/community/index.tsx, src/components/app/community/community-hotBoard.tsx, src/components/app/community/community-tab.tsx, src/hooks/api/community/UseApiComminity.ts
> ### fix: #61 커뮤니티 정렬 필터 수정
---
- 커뮤니티 정렬 필터 수정
- 커밋 내용 참조
- closes: #61
=> fix: #61 커뮤니티 정렬 필터 수정

package.json, pnpm-lock.yaml, src/api/index.ts, src/app/community/index.tsx, src/app/signin/index.tsx, src/app/signup/complete/index.tsx, src/app/signup/consent/index.tsx, src/app/signup/index.tsx, src/components/app/signup/certificate-box.tsx, src/components/app/signup/consent/text-with-checkbox.tsx, src/components/common/Button.tsx, src/components/common/confetti/Confetti.tsx, src/components/layout/header.tsx, src/hooks/api/member/useApiSendVerifyEmail.ts, src/hooks/api/member/useApiSignIn.ts, src/hooks/api/member/useApiSignUp.ts, src/hooks/api/member/useApiVerifyEmail.ts
> ### 회원가입 및 로그인 API 연동 (소셜 제외)
---
- 회원가입 및 로그인 API 연동
- 커밋 내용 참조
- closes: #40
=> 회원가입 및 로그인 API 연동 (소셜 제외)

package.json, pnpm-lock.yaml, src/app/signin/index.tsx, src/components/layout/header.tsx, src/store/user/index.ts
=> fix: #73 Fix Wrong user login state

src/app/predict/index.tsx, src/components/app/predict/newsletter/news-image.tsx
=> fix: #73 Fix newletter issue

src/app/news/index.tsx, src/assets/common/ic_not_data.svg, src/components/app/predict/newsletter/news-image.tsx, src/components/common/NotData.tsx
=> feat: #73 Added blank screen design to newsletter search

src/app/signup/complete/index.tsx, src/app/signup/consent/index.tsx, src/app/signup/index.tsx
=> fix: #73 Add signup complete screen username

src/app/home/index.tsx, src/components/app/predict/newsletter/news-content.tsx
=> fix: #73 Fix Main Button · NewsLetter Tag

src/app/oauth2/redierct/index.tsx, src/app/signin/index.tsx, src/app/signup/consent/index.tsx, src/app/signup/index.tsx, src/routes/index.tsx, src/store/user/index.ts
---
- 카카오/구글 회원가입 api 연동
- 커밋 내용 참조
-
=> feat: #79 카카오/구글 회원가입 api 연동

src/app/oauth2/redierct/index.tsx, src/components/layout/index.tsx, src/store/user/index.ts
---
- 소셜 로그인시 accessToken 저장 로직 수정
- 전역변수 → localstorge 저장
-
=> fix: #79 accessToken 저장 로직 수정

src/app/home/index.tsx
=> fix: 토큰 오류로 인해 임시 커뮤니티 비활성화

src/app/home/index.tsx
=> fix: 사용하지 않는 임포트 파일 삭제
